### ISSUE TITLE
Can you publish it to jitpack?

### ISSUE THREAD

**Issue by Cyberavater** [fluxo-kt/fluxo-io#12]
It seems like this library is stable enough. If you publish it in Jitpack, it'll be easier to integrate into the project.
Benefits:

- -SNAPSHOT will provide the version of the latest commit build
- Easier accessibility might give it more traction, which might help it reach a stable release through bug reports and early testing.
- The SNAPSHOT versions don't need any release tag and are automatically built by jitpack servers.

https://jitpack.io/#fluxo-kt/fluxo-io/-SNAPSHOT

**Comment by art-shen** [comment]
Sure, thanks for the nudge!
I will try to publish it as soon as possible (hopefully this week) and ping you here afterwards.

**Comment by art-shen** [comment]
@Cyberavater, sorry it took me so long, but now the library is published in the Maven Central:<br>
[![Version][badge-mvn]][mvn]

And you can use snapshots from either Maven Central or the JitPack:<br>
[![Snapshot Version][badge-snapshot]][snapshot] [![JitPack][badge-jitpack]][jitpack]

[mvn]: https://mvnrepository.com/artifact/io.github.fluxo-kt/fluxo-io
[badge-mvn]: https://img.shields.io/maven-central/v/io.github.fluxo-kt/fluxo-io?logo=apachemaven&labelColor=c71a36&color=666

[snapshot]: https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/fluxo-kt/fluxo-io
[badge-snapshot]: https://img.shields.io/badge/dynamic/xml?color=666&logo=apachemaven&labelColor=c71a36&label=&query=%2F%2Fversion%5Blast%28%29%5D&url=https%3A%2F%2Fs01.oss.sonatype.org%2Fcontent%2Frepositories%2Fsnapshots%2Fio%2Fgithub%2Ffluxo-kt%2Ffluxo-io%2Fmaven-metadata.xml

[jitpack]: https://www.jitpack.io/#fluxo-kt/fluxo-io
[badge-jitpack]: https://www.jitpack.io/v/fluxo-kt/fluxo-io.svg

**Comment by Cyberavater** [comment]
Thanks, appreciate ya!
